# Generated by Django 5.1.4 on 2026-07-30 20:40

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Medecin')
    Group.objects.get_or_create(name='Comptable')


def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Medecin', 'Comptable']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
