# Generated by Django 6.0.4 on 2026-07-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Radiographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='radiographies/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('classe_predite', models.CharField(choices=[('Normal', 'Normal (Sain)'), ('Pneumonie', 'Pneumonie'), ('En attente', 'En attente')], default='En attente', max_length=20)),
                ('pourcentage_confiance', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiographies', to='medical_app.patient')),
            ],
        ),
    ]
