# Generated by Django 6.0.4 on 2026-07-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiographie',
            name='validation_medecin',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmé', "Confirmé (L'IA a raison)"), ('Corrigé (Normal)', "Corrigé (C'est Normal)"), ('Corrigé (Pneumonie)', "Corrigé (C'est une Pneumonie)")], default='En attente', max_length=30),
        ),
    ]
