# Generated by Django 6.0.4 on 2026-07-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0002_radiographie_validation_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiographie',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
    ]
