# Generated by Django 6.0.7 on 2026-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0003_radiographie_heatmap_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fumeur',
            field=models.CharField(blank=True, choices=[('Non-fumeur', 'Non-fumeur'), ('Fumeur', 'Fumeur'), ('Ancien fumeur', 'Ancien fumeur')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes_medecin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='poids',
            field=models.FloatField(blank=True, help_text='Poids en kg', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='taille',
            field=models.FloatField(blank=True, help_text='Taille en cm', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
