# Generated by Django 6.0.7 on 2026-07-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0004_patient_adresse_patient_allergies_patient_fumeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='carte_identite',
            field=models.FileField(blank=True, help_text="Scan ou code de la carte d'identité (Image ou PDF)", null=True, upload_to='patients/cartes/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/'),
        ),
    ]
