# Generated by Django 6.0.7 on 2026-07-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0005_patient_carte_identite_patient_photo_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='carte_identite',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photo_profil',
        ),
    ]
