# Generated by Django 6.0.7 on 2026-07-31 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0006_remove_patient_carte_identite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedecinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, default='Pneumologue', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('inpe', models.CharField(blank=True, max_length=50, verbose_name='INPE')),
                ('adresse_cabinet', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
