# Generated by Django 6.0.7 on 2026-07-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0007_medecinprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecinprofile',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
