# Generated by Django 6.0.7 on 2026-08-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0008_medecinprofile_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiographie',
            name='statut_analyse',
            field=models.CharField(choices=[('EN_COURS', 'Analyse en cours'), ('TERMINEE', 'Analyse terminée'), ('ERREUR', 'Erreur')], default='TERMINEE', max_length=20),
        ),
    ]
