# Generated by Django 6.0.7 on 2026-08-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0009_radiographie_statut_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiographie',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='radiographies/thumbnails/'),
        ),
    ]
