# Generated by Django 6.0.4 on 2026-08-05 18:44

import medical_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0010_radiographie_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=medical_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=medical_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='antecedents_medicaux',
            field=medical_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes_medecin',
            field=medical_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=medical_app.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
    ]
